public class cipher{
    public static void main(String[] args)
    {
        char[] alphabet = {'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O',
            'P','Q','R','S','T','U','V','W','X','Y','Z'};
        String ciph ="YUTYJGAMNZKXOTRGCHXOTMNKXYKRLZURKZNOSQTUCNKXYZGZKNKXXKRAIZGTIKZUIUSSATOIGZKCOZNNKXNAYHGTJYVGXKTZYSOMNZYNKZNUAMNZRKYYKTCOZNZNKRGVYKULZOSKHAZCOZNNKXUCTZNKXKBKXYKUHZGOTKJUTNKXRKGBOTMZNKOXNUAYKGLZKXZNKYNUXZBOYOZYAHYKWAKTZZUNKXSGXXOGMKZNKECKXKATJKXZNKOSVXKYYOUTZNGZYNKCGYARZOSGZKREMUOTMZUPUOTNKXNAYHGTJGTJLXUSZNGZZOSKZUZNKVXKYKTZYNKNGJJUTKTUZNOTMZUJOYZAXHZNKOXHKROKLZNGZYNKCGYGCGOZOTMNOYXKZAXTOTIUSLUXZNUVOTMGMGOTYZNUVKZNGZNOYPUAXTKEZUHXGFORCUARJXKYARZOTGYNUXZYZGEUTREGLZKXCNOINNKCUARJIUSKZULKZINNKXUXZNGZNKCUARJCXOZKLUXNKXZUPUOTNOSOTGTEIGYKZNGZZNKECUARJYUUTVXKYKTZGATOZKJLXUTZZUZNKOXLGSOROKYGTJZNKCUXRJZNOYNUVKYNKYZORRLUYZKXKJZURKZNKXVGXKTZYQTUCZNGZYNKCGYGJKYKXZKJCOLKJKVKTJKTZTUCZNGZYNKNGJXKROKBKJZNKOXTKIKYYOZOKYUTNKXUCTNGTJYLUXGROBOTMGLZKXZNKKIRGZULGSGXXOGMKCNOINCGYZUTARROLEZNKIURRGVYKULZNKLOXYZGZZKSVZCUARJHKZUUSAINOTJKKJZNKYKZULHXORROGTZY";
        char[] chars = ciph.toCharArray();
        decrypt(chars,alphabet);
    }

/*
* Basic caesar cipher decrypter 
* Uses modular arithmetic to shift the alphabet
* The decrypt() methos takes an alphabet char[] and the cipher as a char[]
* two for each loops, outer one for each alphabetical shift and the inner one for each character of the cipher
* performs the modular arithmetic on the char values. Repeats this for each key length (0-26).
* This is a brute force method that tests every possible shift
* I found that the correct is a key shift of 26
SONSDAUGHTERINLAWBRINGHERSELFTOLETHIMKNOWHERSTATEHERRELUCTANCETOCOMMUNICATEWITHHERHUSBANDSPARENTSMIGHTSHETHOUGHTLESSENWITHTHELAPSEOFTIMEBUTWITHHEROWNTHEREVERSEOBTAINEDONHERLEAVINGTHEIRHOUSEAFTERTHESHORTVISITSUBSEQUENTTOHERMARRIAGETHEYWEREUNDERTHEIMPRESSIONTHATSHEWASULTIMATELYGOINGTOJOINHERHUSBANDANDFROMTHATTIMETOTHEPRESENTSHEHADDONENOTHINGTODISTURBTHEIRBELIEFTHATSHEWASAWAITINGHISRETURNINCOMFORTHOPINGAGAINSTHOPETHATHISJOURNEYTOBRAZILWOULDRESULTINASHORTSTAYONLYAFTERWHICHHEWOULDCOMETOFETCHHERORTHATHEWOULDWRITEFORHERTOJOINHIMINANYCASETHATTHEYWOULDSOONPRESENTAUNITEDFRONTTOTHEIRFAMILIESANDTHEWORLDTHISHOPESHESTILLFOSTEREDTOLETHERPARENTSKNOWTHATSHEWASADESERTEDWIFEDEPENDENTNOWTHATSHEHADRELIEVEDTHEIRNECESSITIESONHEROWNHANDSFORALIVINGAFTERTHEECLATOFAMARRIAGEWHICHWASTONULLIFYTHECOLLAPSEOFTHEFIRSTATTEMPTWOULDBETOOMUCHINDEEDTHESETOFBRILLIANTS
* FIRST 30 CHARACTERS = SONSDAUGHTERINLAWBRINGHERSELFT
*/

    public static void decrypt(char[] chars,char[] alphabet){
        for(int key = 0; key <26; key++){
            String plainText = "";
            for(int i =0; i < chars.length; i++){
                int p = (chars[i] - key- 'A' + 26) % 26;
                plainText += alphabet[p];
            }
            System.out.println("The key is "+key);
            System.out.println(plainText);
            plainText = "";
       }
        
    }
}

